# Generated by Django 2.2.1 on 2019-05-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='traffic_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('bread', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'traffic_data',
            },
        ),
    ]
