# Generated by Django 2.2.1 on 2019-05-22 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traffic_data',
            old_name='bread',
            new_name='flow',
        ),
    ]
